// apps/showcase/solid-real-world-rick-morty/src/pages/location/view.tsx
import { createQueryResource } from '@farfetched/solid';
import { Link } from 'atomic-router-solid';
import { For, Suspense } from 'solid-js';

import { characterRoute } from '../../entities/character';
import { locationQuery, residentsQuery } from './model';

function LocationPage() {
  const [location] = createQueryResource(locationQuery);
  const [residents] = createQueryResource(residentsQuery);

  return (
    <Suspense fallback={'Loading ...'}>
      <h1>{location().name}</h1>
      <p>Type: {location().type}</p>
      <p>Dimension: {location().dimension}</p>

      <Suspense fallback={'Loading ...'}>
        <h2>Residents</h2>
        <ul>
          <For each={residents()}>
            {(resident) => (
              <li>
                <Link to={characterRoute} params={{ characterId: resident.id }}>
                  {resident.name}
                </Link>
              </li>
            )}
          </For>
        </ul>
      </Suspense>
    </Suspense>
  );
}
export { LocationPage };

// apps/showcase/solid-real-world-rick-morty/src/entities/location/view.tsx
import { Link } from 'atomic-router-solid';
import { Static } from 'runtypes';

import { Location } from './contract';
import { locationRoute } from './model';

function LocationDetails(props: {
  title: string;
  location: Static<typeof Location>;
}) {
  return (
    <section>
      <h2>
        {props.title}: {props.location.name}
      </h2>
      <table>
        <tbody>
          <tr>
            <th>Type</th>
            <td>{props.location?.type}</td>
          </tr>
          <tr>
            <th>Dimension</th>
            <td>{props.location?.dimension}</td>
          </tr>
        </tbody>
      </table>
      <Link to={locationRoute} params={{ locationId: props.location.id }}>
        Open
      </Link>
    </section>
  );
}

export { LocationDetails };
