// apps/showcase-solid-real-world-rick-morty/src/pages/main/view.tsx
import { createQueryResource } from '@farfetched/solid';
import { Link } from 'atomic-router-solid';
import { useUnit } from 'effector-solid';
import { For, Show, Suspense } from 'solid-js';

import { characterRoute, characterListRoute } from '../../entities/character';
import { Pagination } from '../../features/pagination';
import { $currentPage, allCharactersQuery } from './model';

function MainPage() {
  const [data] = createQueryResource(allCharactersQuery);
  const { currentPage } = useUnit({
    currentPage: $currentPage,
  });

  return (
    <>
      <h1>Main page</h1>
      <Suspense fallback={'Loading...'}>
        <Show when={data()}>
          {({ info, results }) => (
            <>
              <ol>
                <For each={results}>
                  {(character) => (
                    <li value={character.id}>
                      <Link
                        to={characterRoute}
                        params={{ characterId: character.id }}
                      >
                        {character.name}
                      </Link>
                    </li>
                  )}
                </For>
              </ol>
              <Pagination
                currentPage={currentPage()}
                route={characterListRoute}
                info={info}
              />
            </>
          )}
        </Show>
      </Suspense>
    </>
  );
}

export { MainPage };

// apps/showcase/react-real-world-pokemons/src/pages/main/view.tsx
import { useGate, useList, useUnit } from 'effector-react';
import { useParams, Link } from 'react-router-dom';

import { Pagination } from '../../features/pagination';
import { $pending, $pokemonList, $totalPages, MainPageGate } from './model';

export function MainPage() {
  const params = useParams();
  const currentPage = Number(params['page'] ?? 1);
  useGate(MainPageGate, { page: currentPage });

  const { totalPages, pending } = useUnit({
    totalPages: $totalPages,
    pending: $pending,
  });

  const items = useList($pokemonList, {
    fn: (item) => (
      <li value={item.id}>
        <Link to={`/pokemon/${item.id}`}>{item.name}</Link>
      </li>
    ),
  });

  return (
    <>
      <h1>Main page</h1>
      {!pending && <ol>{items}</ol>}
      {pending && <p>Loading...</p>}
      {totalPages && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          pathname="/pokemons"
        />
      )}
    </>
  );
}
