// apps/showcase/solid-real-world-rick-morty/src/pages/main/view.tsx
import { createQueryResource } from '@farfetched/solid';
import { Link } from 'atomic-router-solid';
import { useUnit } from 'effector-solid';
import { For, Show } from 'solid-js';

import { characterRoute, characterListRoute } from '../../entities/character';
import { Pagination } from '../../features/pagination';
import { $currentPage, characterListQuery } from './model';

function MainPage() {
  const { data, pending } = createQueryResource(characterListQuery);
  const { currentPage } = useUnit({
    currentPage: $currentPage,
  });

  return (
    <>
      <h1>Main page</h1>
      <Show when={!pending()} fallback={'Loading...'}>
        <ol>
          <For each={data()?.results}>
            {(character) => (
              <li value={character.id}>
                <Link
                  to={characterRoute}
                  params={{ characterId: character.id }}
                >
                  {character.name}
                </Link>
              </li>
            )}
          </For>
        </ol>
        <Pagination
          currentPage={currentPage()}
          route={characterListRoute}
          info={data()?.info}
        />
      </Show>
    </>
  );
}

export { MainPage };

// apps/showcase/react-real-world-pokemons/src/pages/main/view.tsx
import { useGate, useList, useUnit } from 'effector-react';
import { useParams, Link } from 'react-router-dom';

import { Pagination } from '../../features/pagination';
import { $pending, $pokemonList, $totalPages, MainPageGate } from './model';

export function MainPage() {
  const params = useParams();
  const currentPage = Number(params['page'] ?? 1);
  useGate(MainPageGate, { page: currentPage });

  const { totalPages, pending } = useUnit({
    totalPages: $totalPages,
    pending: $pending,
  });

  const items = useList($pokemonList, {
    fn: (item) => (
      <li value={item.id}>
        <Link to={`/pokemon/${item.id}`}>{item.name}</Link>
      </li>
    ),
  });

  return (
    <>
      <h1>Main page</h1>
      {!pending && <ol>{items}</ol>}
      {pending && <p>Loading...</p>}
      {totalPages && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          pathname="/pokemons"
        />
      )}
    </>
  );
}
