// apps/showcase/solid-real-world-rick-morty/src/pages/episodes_list/view.tsx
import { createQueryResource } from '@farfetched/solid';
import { Link } from 'atomic-router-solid';
import { useUnit } from 'effector-solid';
import { For, Show } from 'solid-js';

import { episodeListRoute, episodeRoute } from '../../entities/episode';
import { Pagination } from '../../features/pagination';
import { $currentPage, episodesQuery } from './model';

function EpisodesListPage() {
  const { currentPage } = useUnit({ currentPage: $currentPage });
  const { data, pending } = createQueryResource(episodesQuery);

  return (
    <>
      <h1>Episodes</h1>

      <Show when={!pending()} fallback={'Loading...'}>
        <ol>
          <For each={data()?.results}>
            {(episode) => (
              <li value={episode.id}>
                <Link to={episodeRoute} params={{ episodeId: episode.id }}>
                  {episode.name}
                </Link>
              </li>
            )}
          </For>
        </ol>
        <Pagination
          currentPage={currentPage()}
          info={data()?.info}
          route={episodeListRoute}
        />
      </Show>
    </>
  );
}

export { EpisodesListPage };

// apps/showcase/react-real-world-pokemons/src/pages/main/view.tsx
import { useGate, useList, useUnit } from 'effector-react';
import { useParams, Link } from 'react-router-dom';

import { Pagination } from '../../features/pagination';
import { $pending, $pokemonList, $totalPages, MainPageGate } from './model';

export function MainPage() {
  const params = useParams();
  const currentPage = Number(params['page'] ?? 1);
  useGate(MainPageGate, { page: currentPage });

  const { totalPages, pending } = useUnit({
    totalPages: $totalPages,
    pending: $pending,
  });

  const items = useList($pokemonList, {
    fn: (item) => (
      <li value={item.id}>
        <Link to={`/pokemon/${item.id}`}>{item.name}</Link>
      </li>
    ),
  });

  return (
    <>
      {!pending && <ol>{items}</ol>}
      {pending && <p>Loading...</p>}
      {totalPages && (
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          pathname="/pokemons"
        />
      )}
    </>
  );
}
